# docker run --rm --label=jekyll -v "$(pwd)":/srv/jekyll  -it -p 4000:4000 jekyll/jekyll jekyll --config _config.dev.yml serve --watch --incremental
jekyll:
    image: jekyll/jekyll
    command: jekyll serve --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll